openapi: 3.0.0
info:
  description: 'Carbon Aware REST API'
  version: 0.1.0
  title: Carbon Aware REST API

paths:
  '/emissions/forecasts/current':
    get:
      summary: Get the current forecasted marginal carbon intensity for a given set of locations.
      description: Gets the most recent marginal carbon intensity forecast and returns the optimal start time for a window of a given duration.
      operationId: getCurrentMarginalCarbonIntensityForecast
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  '$ref': '#/components/schemas/EmissionsForecast'
              examples: 
                carbon-intensity-forecast-response:
                  '$ref': '#/components/examples/marginal-carbon-intensity-forecast-example'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/CarbonAwareError'
    parameters:
    - name: locations
      in: query
      description: 'Array of names of the locations to be forecasted'
      required: true
      schema:
        type: array
      example: eastus
    - name: windowSize
      in: query
      description: 'The size/granularity (in minutes) of the rolling average window to report the forecasted average carbon intensity.'
      required: false
      schema:
        type: integer
      example: 60
    - name: startTime
      in: query
      description: 'Start the rolling window average at the specified start time or first datapoint thereafter.'
      required: false
      schema:
        type: string
        format: date-time
      example: '2022-05-23T00:00:00Z'
    - name: endTime
      in: query
      description: 'Stop the rolling window average when it reaches the specified end time or the last datapoint before that.'
      required: false
      schema:
        type: string
        format: date-time
      example: '2022-05-23T02:30:00Z'
components:
  schemas:
    EmissionsForecast:
      type: object
      properties:
        generatedAt:
          type: string
          format: date-time
        location:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        windowSize:
          type: integer
        optimalDataPoint:
          '$ref': '#/components/schemas/EmissionsData'
        forecastData:
          type: array
          items:
            '$ref': '#/components/schemas/EmissionsData'

    EmissionsData:
      type: object
      properties:
        location:
          type: string
        timestamp:
          type: string
          format: date-time
        duration:
          type: integer
        value:
          type: number
          format: float

    CarbonAwareError:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        traceId:
          type: string
        errors:
          type: object
    
  examples:    
    marginal-carbon-intensity-forecast-example:
      summary: An example response from an emissions forecast request.
      value: [
        {
          "generatedAt": "2022-05-23T00:00:00Z",
          "optimalDataPoint": {
            "location": "eastus",
            "timestamp": "2022-05-23T00:10:00Z",
            "duration": 5,
            "value": 173.3
          },
          "location": "eastus",
          "startTime": "2022-05-23T00:00:00Z",
          "endTime": "2022-05-23T00:21:00Z",
          "forecastData": [
            {
              "location": "eastus",
              "timestamp": "2022-05-23T00:05:00Z",
              "duration": 5,
              "value": 195.2
            },
            {
              "location": "eastus",
              "timestamp": "2022-05-23T00:10:00Z",
              "duration": 5,
              "value": 173.3
            },
            {
              "location": "eastus",
              "timestamp": "2022-05-23T00:15:00Z",
              "duration": 5,
              "value" 222.4
            },
            {
              "location": "eastus",
              "timestamp": "2022-05-23T00:20:00Z",
              "duration": 5,
              "value" 200.1
            },
          ]
        }
      ]