name: Auto PR from Upstream

on:
  push:
    branches: katantia-automerge
  schedule:
    - cron: '0 0 * * Wed' # Every Wednesday at midnight

env:
  OWNER: "microsoft"
  REPO: "carbon-aware-sdk"
  UPSTREAM: "Green-Software-Foundation/carbon-aware-sdk"
  PR-BRANCH: "upstream-pr-${GITHUB_RUN_ID}"


jobs:
  check-for-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Auto-Merge Script
      id: auto-merge
      run: |
        ./ms-internal/git-merge.sh upstream-pr-${GITHUB_RUN_ID}
        echo ::set-output name=exit_code::$?
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Open PR against in Repo Branch      
    #   uses: octokit/request-action@v2.x
    #   if: steps.auto-merge.outputs.exit-code==0
    #   with:
    #     route: POST /repos/{owner}/{repo}/pulls
    #     owner: ${OWNER}
    #     repo: ${REPO}
    #     title: "Automated Merge Upstream Reposistory into Main"
    #     head: upstream-pr-${GITHUB_RUN_ID}
    #     base: dev
    #     body: "Automatically triggered PR from GSF to MSFT Repository"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
