name: Docker Web API Build

# on:
#   push:
#     paths:
#       - 'src/dotnet/**'
#       - '.github/workflows/**'
#   pull_request:
#     branches: [ dev, main ]
#     paths:
#       - 'src/dotnet/**'


on: 
  push:
    branches:
    - "kanishk/cli-first-pass"

jobs:
#   container-build-step:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
    
#     - name: Docker Target Build
#       run: docker build --target=build . -f CarbonAware.WebApi/Dockerfile -t ca-api-build
#       working-directory: ./src/dotnet

#     - name: Docker Unit Test
#       run: docker run -w //src/CarbonAware.Tests ca-api-build dotnet test
#       working-directory: ./src/dotnet

#     - name: Docker Basic Plugin Test
#       run: docker run -w //src/CarbonAware.Plugins.BasicJsonPlugin.Tests ca-api-build dotnet test
#       working-directory: ./src/dotnet

  container-publish-step:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Target Final
        run: docker build . -f CarbonAware.WebApi/Dockerfile -t ca-api
        working-directory: ./src/dotnet
        
      - name: Docker Run Container
        run: |
          docker run -d --name publish-container -p 8080:80 ca-api
          docker container ls
          docker exec publish-container apt update
          docker exec publish-container apt install -y curl
          docker exec curl 0.0.0.0:80/emissions/bylocation
      
      - name: Docker Ping Container
        run: curl -v 0.0.0.0:8080/emissions/bylocation

