name: Docker Web API Build

# on:
#   push:
#     paths:
#       - 'src/dotnet/**'
#       - '.github/workflows/**'
#   pull_request:
#     branches: [ dev, main ]
#     paths:
#       - 'src/dotnet/**'


on: 
  push:
    branches:
    - "kanishk/cli-first-pass"

jobs:
  container-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Docker Build All
      run: docker build . -f CarbonAware.WebApi/Dockerfile -t ca-api
      working-directory: ./src/dotnet

    - name: Docker Build Step
      run: docker build --target=build . -f CarbonAware.WebApi/Dockerfile -t ca-api-build
      working-directory: ./src/dotnet

    - name: Docker Unit Test
      run: docker run -w //src/CarbonAware.Tests ca-api-build dotnet test
      working-directory: ./src/dotnet

    - name: Docker Basic Plugin Test
      run: docker run -w //src/CarbonAware.Plugins.BasicJsonPlugin.Tests ca-api-build dotnet test
      working-directory: ./src/dotnet

    - name: Docker Ping Container
      run: |
        docker run --network host -p 8080:80 ca-api 
        curl localhost:8080/emissions/bylocation
