name: Docker Web API Build

on:
  push:
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'

jobs:
  container-build-step:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Docker Target Build
      run: docker build --target=build . -f CarbonAware.WebApi/Dockerfile -t ca-api-build
      working-directory: ./src/dotnet

    - name: Docker Unit Test
      run: docker run -w //src/ ca-api-build dotnet test
      working-directory: ./src/dotnet

  container-publish-step:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Target Final
        run: docker build . -f CarbonAware.WebApi/Dockerfile -t ca-api
        working-directory: ./src/dotnet
        
      - name: Docker Run Container
        run: |
          docker run -d --name publish-container -p 8080:80 ca-api
          docker container ls
          
      - name: Docker Wget in container
        run: |
          docker exec publish-container apt update
          docker exec publish-container apt install -y wget
          docker exec publish-container wget -t 5 --waitretry=5 0.0.0.0:80/emissions/bylocation?location=eastus

      - name: Docker Ping From Host
        run: |
          wget -t 5 --waitretry=5 0.0.0.0:8080/emissions/bylocation?location=eastus

