name: BUILD CLI in DOTNET

on:
  push:
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet
    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Regression Tests 'Get Emission Data for AZure Region EastUs'
      run: ./bin/Debug/net6.0/CarbonAwareCLI -l eastus -d ./bin/Debug/net6.0/data-files/dummy-data-azure-emissions.json
      working-directory: './src/dotnet/CarbonAware.CLI/'
