name: Docker Web API Build

# on:
#   push:
#     paths:
#       - 'src/dotnet/**'
#       - '.github/workflows/**'
#   pull_request:
#     branches: [ dev, main ]
#     paths:
#       - 'src/dotnet/**'


on: 
  push:
    branches:
    - "kanishk/cli-first-pass"

jobs:
  app-build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/dotnet/CarbonAware.WebApi

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/dotnet/CarbonAware.WebApi

    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/dotnet/CarbonAware.WebApi
  
  container-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Build All
      run: docker build . -f CarbonAware.WebApi/Dockerfile -t ca-api
      working-directory: ./src/dotnet

    - name: Docker Build Step
      run: docker build --target=build . -f CarbonAware.WebApi/Dockerfile -t ca-api-build
      working-directory: ./src/dotnet

    - name: Docker Unit Test
      run: docker run -w //src/CarbonAware.Tests ca-api-build dotnet test
      working-directory: ./src/dotnet

    - name: Docker Basic Plugin Test
      run: docker run -w //src/CarbonAware.Plugins.BasicJsonPlugin.Tests ca-api-build dotnet test
      working-directory: ./src/dotnet
