name: Docker Web API Build

# on:
#   push:
#     paths:
#       - 'src/dotnet/**'
#       - '.github/workflows/**'
#   pull_request:
#     branches: [ dev, main ]
#     paths:
#       - 'src/dotnet/**'


on: 
  push:
    branches:
    - "kanishk/cli-first-pass"

jobs:
  app-build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    defaults:
      run:
        working-directory: ./src/dotnet/CarbonAware.WebApi
    steps:

    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore "CarbonAware.WebApi/CarbonAware.WebApi.csproj"

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal
  
  container-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet/CarbonAware.WebApi
    steps:
    - uses: actions/checkout@v2

    - name: Docker Build All
      run: docker build . -f CarbonAware.WebApi/Dockerfile -t ca-api

    - name: Docker Build Step
      run: docker build --target=build . -f CarbonAware.WebApi/Dockerfile -t ca-api-build

    - name: Docker Unit Test
      run: docker run -w //src/CarbonAware.Tests ca-api-build dotnet test

    - name: Docker Basic Plugin Test
      run: docker run -w //src/CarbonAware.Plugins.BasicJsonPlugin.Tests ca-api-build dotnet test
