name: using CarboneAware Github action in sample pipeline

on:
  push:
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CarboneAWare metrics
      id: carboneaware-metrics
      uses: Green-Software-Foundation/carbon-aware-sdk/src/dotnet@container-build
      with:
        location: westeurope
        #config: /carbon-aware.json
        #fromTime:
        #toTime
        
    - name: Get Selected Region
      run: echo "${{ steps.carboneaware-metrics.outputs}}"
