name: using CarboneAware Github action in sample pipeline

on:
  push:
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet
    steps:
        
    - name: CarboneAWare metrics
      id: carboneaware-metrics
      uses: Green-Software-Foundation/carbon-aware-sdk/src/dotnet@container-build
      env:
        GREETINGS: 'Hello, .NET developers!' # ${{ secrets.GITHUB_TOKEN }}
      with:
        location: westeurope
        config: carbon-aware.json
